version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: CinemaNode
      MYSQL_USER: user_cinema
      MYSQL_PASSWORD: azerty
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/lib/mysql

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:
    driver: local