version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CinemaNode
      MYSQL_USER: my_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    environment:
      DATABASE_URL: mysql://root:root@db:3306/CinemaNode
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
    driver: local

